package ru.gpsantiradar.app

enum class CarMenuItem {
    UPDATE_DATABASE,
    OVERSPEED_THRESHOLD,
    HUD_TRANSPARENCY,
    ZONE_TRANSPARENCY,
    ACTIVE_ZONE_TRANSPARENCY,
    ZONE_DISPLAY,
    AUTO_ROTATE_MAP,
    THEME,
    MAPKIT_KEY,
    ABOUT,
    EXIT
}
